version: '3.8'
services:
  # El servidor web (PHP + Apache)
  web:
    build: .
    container_name: producto2_web
    ports:
      - "8003:80" # Tu web se verá en http://localhost:8003
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # La base de datos (MySQL)
  db:
    image: mysql:8.0
    container_name: producto2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: producto2_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Puerto para MySQL
    volumes:
      - db_data:/var/lib/mysql

  # El gestor de BBDD (PhpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: producto2_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80" # Tu PhpMyAdmin se verá en http://localhost:8082
    restart: always

volumes:
  db_data: